### ISSUE TITLE
Migration help

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#78] opened 2018-10-12 16:28 UTC
Earlier version of hapi-mongo-models had quite good examples (been using it for years), now when "forced" to migration to hapi17.6, I find myself headbanging with current release of hapi-mongo-models, special the limited information and lack of examples...

Does their exists more examples for hapi somewhere I can't find?

**Comment by jedireza** [comment] 2018-10-13 02:48
Closing as duplicate of #79

**Closed by jedireza** 2018-10-13 02:48 UTC
