### ISSUE TITLE
BaseModel's cursor not being released.

### ISSUE THREAD

**Issue by TomerAvni** [jedireza/hapi-mongo-models#57] opened 2016-05-24 05:33 UTC
Hi,
I am using this great library on production and it worked perfectly until a few days ago.
To put it simple, after some usage of the API (vary between 5 min to 20 hours), the BaseModel (hapi-mongo-models) simply timeouts on every request (that is - the callback function is not called - not even as an error).
However, if during its "stuck" mode I evaluate a JS expression (with eval) that creates a brand new mongoDB proxy (using the native 'mongodb'), it works perfectly fine (hence I think it has to do with BaseModel and the fact it is a singleton-ish).
This lead me to believe that the db's cursor itself is not being released properly.
**** The following is an assumption (based on some local code).
I have drilled down to the cursor.js file (part of the native library) and the issue seem to be around the nextObject (line 647, mongodb@2.1.19), where no object nor error is being captured by the document and it seem to be entering some deadlock.
Unfortunately I can't easily reproduce it.
Any help, debugging, ideas are welcomed.

THANKS.

** I've moved to the newest frame version which did not help.
I've also opened a SW case http://stackoverflow.com/questions/37371421/hapijs-hapi-mongo-models-server-stuck-on-504-http-error

**Comment by Kyii** [comment] 2016-05-24 12:49
Hello, 
i have also used this very nice and reliable library as part of "frame" in production for over a year. i never had any problems. 
but recently i am also experience 504 timeout errors after varying amounts of time for every request. 
the situation seems to be similar to TomerAvnis.

Any help or debugging ideas are very much appreciated.

node -v v4.3.0
hapi@11.1.4
hapi-mongo-models@4.2.0
mongodb@2.1.19

Thanks!

**Comment by Kyii** [comment] 2016-05-24 13:10
this could be very much related. because i realized that the error might have been occurred after updating to mongodb@2.1.19 from mongodb@2.1.18
so going back to mongodb@2.1.18 might help. i will try.

https://github.com/ParsePlatform/parse-server/issues/1855
https://jira.mongodb.org/browse/NODE-717

**Comment by TomerAvni** [comment] 2016-05-24 14:37
Downgrading didn't work for me.
**Important update**
It is obviously has to do with mongo (or mongodb proxy or both), so my quick&dirty **workaround**, is polling my node server (which uses the proxy to mongo) every 1 minute using a simple curl.
I have no idea why it works (stealth mode?), but it does work. Since I am calling the same resource it must be cached, but still.. it works.

**Comment by jedireza** [comment] 2016-05-24 19:51
Thanks for opening an issue. I've tagged this as "bug in dependency" for the time being. Unless of course we can determine changes are needed in this module.

The latest comment in https://jira.mongodb.org/browse/NODE-717 says:

> This issue would only affect single server instance connections not replicaset or sharded connections.

> There are some bug fixes going into the 2.1.20 maintenance release tomorrow that might improve the situation as there are some weird corner cases that we fixed that might improve the problem.

> It will be out tomorrow.

I'll leave this issue open for now. Please post updates here as they develop.

**Comment by Kyii** [comment] 2016-05-25 16:17
i can confirm after 24 hours: downgrading to mongodb@2.1.18 solved the issue for me. 

thanks jedireza for looking into the issue!

**Comment by jedireza** [comment] 2016-05-25 19:09
Thanks for the update @Kyii. `mongodb@2.1.20` was released about 10ish hours ago. Would either of you be willing to try it out and see if the issue was resolved?

**Comment by TomerAvni** [comment] 2016-05-26 06:10
I will.

**Comment by TomerAvni** [comment] 2016-05-29 06:55
Unfortunately it was not resolved.

**Comment by jedireza** [comment] 2016-05-31 18:53
Thanks @TomerAvni. I wonder if the title of this issue is accurate. Should we keep this issue open since it seems to be an issue outside of this module?

**Comment by TomerAvni** [comment] 2016-05-31 20:35
Well I still don't know if it related to this module. It doesn't seem to be strictly related, but I figured someone along the way might resolve it under the same state.

Tomer.

**Comment by Kyii** [comment] 2016-06-02 09:37
as far as i can tell the issue was fixed in mongodb@2.1.21. i will try and report back.
see: https://jira.mongodb.org/browse/NODE-718

**Comment by jedireza** [comment] 2016-06-02 19:23
Thanks for the updates @Kyii. @TomerAvni can you give this a try too?

**Comment by TomerAvni** [comment] 2016-06-03 04:31
I will.
Thanks.

Tomer.

**Comment by Kyii** [comment] 2016-06-03 19:16
i can confirm after more than 24 hours that using mongodb@2.1.21 solved the issue.
"...the ping has been re-enabled as default behavior for single server connections" see: https://jira.mongodb.org/browse/NODE-718

**Comment by jedireza** [comment] 2016-06-03 22:55
Thanks @Kyii. @TomerAvni if you could confirm I'd be happy to close this issue. 😃

**Comment by TomerAvni** [comment] 2016-06-04 04:45
OK on my side as well.

Tomer.

**Comment by jedireza** [comment] 2016-06-04 05:19
Thanks everyone.

**Closed by jedireza** 2016-06-04 05:19 UTC
Labels: bug in dependency
